https://ipl-stats-sports-mechanic.s3.ap-south-1.amazonaws.com/ipl/feeds/stats/10011-groupstandings.js?ongroupstandings=_jqjsp&_1682830144855
2019 

https://ipl-stats-sports-mechanic.s3.ap-south-1.amazonaws.com/ipl/feeds/stats/10013-groupstandings.js?ongroupstandings=_jqjsp&_1682830185102=

2021



https://ipl-stats-sports-mechanic.s3.ap-south-1.amazonaws.com/ipl/feeds/stats/10011-groupstandings.js?ongroupstandings=_jqjsp&_1682830204043=

2019

2019
[
    {
        "IPLYear": 2019,
        "Category": "IPL",
        "CompetitionID": "2019",
        "TeamID": "",
        "TeamCode": "MI",
        "TeamName": "Mumbai Indians",
        "TeamLogo": "",
        "Matches": 14,
        "Wins": 9,
        "Loss": 5,
        "Tied": 0,
        "NoResult": 0,
        "Points": 18,
        "Draw": 0,
        "ForTeams": "2380/275.1",
        "AgainstTeam": "2282/277.2",
        "NetRunRate": "0.421",
        "Quotient": 0,
        "OrderNo": "1",
        "IsQualified": "1",
        "LeadBy": 0,
        "Deficit": 0,
        "Performance": "WWLWL"
    },
    {
        "IPLYear": 2019,
        "Category": "IPL",
        "CompetitionID": "2019",
        "TeamID": "",
        "TeamCode": "CSK",
        "TeamName": "Chennai Super Kings",
        "TeamLogo": "",
        "Matches": 14,
        "Wins": 9,
        "Loss": 5,
        "Tied": 0,
        "NoResult": 0,
        "Points": 18,
        "Draw": 0,
        "ForTeams": "2043/274.1",
        "AgainstTeam": "2012/274.5",
        "NetRunRate": "0.131",
        "Quotient": 0,
        "OrderNo": "2",
        "IsQualified": "1",
        "LeadBy": 0,
        "Deficit": 0,
        "Performance": "LWLWL"
    },
    {
        "IPLYear": 2019,
        "Category": "IPL",
        "CompetitionID": "2019",
        "TeamID": "",
        "TeamCode": "DC",
        "TeamName": "Delhi Capitals",
        "TeamLogo": "",
        "Matches": 14,
        "Wins": 9,
        "Loss": 5,
        "Tied": 0,
        "NoResult": 0,
        "Points": 18,
        "Draw": 0,
        "ForTeams": "2207/272.5",
        "AgainstTeam": "2238/278.1",
        "NetRunRate": "0.044",
        "Quotient": 0,
        "OrderNo": "3",
        "IsQualified": "1",
        "LeadBy": 0,
        "Deficit": 0,
        "Performance": "WLWWW"
    },
    {
        "IPLYear": 2019,
        "Category": "IPL",
        "CompetitionID": "2019",
        "TeamID": "",
        "TeamCode": "SRH",
        "TeamName": "Sunrisers Hyderabad",
        "TeamLogo": "",
        "Matches": 14,
        "Wins": 6,
        "Loss": 8,
        "Tied": 0,
        "NoResult": 0,
        "Points": 12,
        "Draw": 0,
        "ForTeams": "2288/269.2",
        "AgainstTeam": "2200/277.5",
        "NetRunRate": "0.577",
        "Quotient": 0,
        "OrderNo": "4",
        "IsQualified": "1",
        "LeadBy": 0,
        "Deficit": 0,
        "Performance": "LLWLL"
    },
    {
        "IPLYear": 2019,
        "Category": "IPL",
        "CompetitionID": "2019",
        "TeamID": "",
        "TeamCode": "KKR",
        "TeamName": "Kolkata Knight Riders",
        "TeamLogo": "",
        "Matches": 14,
        "Wins": 6,
        "Loss": 8,
        "Tied": 0,
        "NoResult": 0,
        "Points": 12,
        "Draw": 0,
        "ForTeams": "2466/270.4",
        "AgainstTeam": "2419/266.2",
        "NetRunRate": "0.028",
        "Quotient": 0,
        "OrderNo": "5",
        "IsQualified": "",
        "LeadBy": 0,
        "Deficit": 0,
        "Performance": "LWWLL"
    },
    {
        "IPLYear": 2019,
        "Category": "IPL",
        "CompetitionID": "2019",
        "TeamID": "",
        "TeamCode": "PBKS",
        "TeamName": "Punjab Kings",
        "TeamLogo": "",
        "Matches": 14,
        "Wins": 6,
        "Loss": 8,
        "Tied": 0,
        "NoResult": 0,
        "Points": 12,
        "Draw": 0,
        "ForTeams": "2429/276.3",
        "AgainstTeam": "2503/277",
        "NetRunRate": "-0.251",
        "Quotient": 0,
        "OrderNo": "6",
        "IsQualified": "",
        "LeadBy": 0,
        "Deficit": 0,
        "Performance": "WLLLL"
    },
    {
        "IPLYear": 2019,
        "Category": "IPL",
        "CompetitionID": "2019",
        "TeamID": "",
        "TeamCode": "RR",
        "TeamName": "Rajasthan Royals",
        "TeamLogo": "",
        "Matches": 14,
        "Wins": 5,
        "Loss": 8,
        "Tied": 0,
        "NoResult": 1,
        "Points": 11,
        "Draw": 0,
        "ForTeams": "2153/257",
        "AgainstTeam": "2192/248.2",
        "NetRunRate": "-0.449",
        "Quotient": 0,
        "OrderNo": "7",
        "IsQualified": "",
        "LeadBy": 0,
        "Deficit": 0,
        "Performance": "LNWWL"
    },
    {
        "IPLYear": 2019,
        "Category": "IPL",
        "CompetitionID": "2019",
        "TeamID": "",
        "TeamCode": "RCB",
        "TeamName": "Royal Challengers Bangalore",
        "TeamLogo": "",
        "Matches": 14,
        "Wins": 5,
        "Loss": 8,
        "Tied": 0,
        "NoResult": 1,
        "Points": 11,
        "Draw": 0,
        "ForTeams": "2146/258.4",
        "AgainstTeam": "2266/254.3",
        "NetRunRate": "-0.607",
        "Quotient": 0,
        "OrderNo": "8",
        "IsQualified": "",
        "LeadBy": 0,
        "Deficit": 0,
        "Performance": "WNLWW"
    }
]


2023
[
    {
        "StandingFlag": "NET",
        "Category": null,
        "CompetitionID": "107",
        "TeamID": "35",
        "TeamCode": "GT",
        "TeamName": "Gujarat Titans",
        "TeamLogo": "https://scores.iplt20.com/ipl/teamlogos/GT.png?v=1",
        "Matches": "8",
        "Wins": "6",
        "Loss": "2",
        "Tied": "0",
        "NoResult": "0",
        "Points": "12",
        "Draw": "0",
        "ForTeams": "1402/155.1",
        "AgainstTeam": "1338/159.2",
        "NetRunRate": "0.638",
        "Quotient": "1.612",
        "OrderNo": "1",
        "IsQualified": null,
        "LeadBy": "0",
        "Deficit": "0",
        "Performance": "W,L,W,W,W",
        "Status": "SAME",
        "MATCH_ID": "894",
        "PrevPosition": "1"
    },
    {
        "StandingFlag": "NET",
        "Category": null,
        "CompetitionID": "107",
        "TeamID": "18",
        "TeamCode": "RR",
        "TeamName": "Rajasthan Royals",
        "TeamLogo": "https://scores.iplt20.com/ipl/teamlogos/RR.png",
        "Matches": "8",
        "Wins": "5",
        "Loss": "3",
        "Tied": "0",
        "NoResult": "0",
        "Points": "10",
        "Draw": "0",
        "ForTeams": "1476/159.2",
        "AgainstTeam": "1332/160.0",
        "NetRunRate": "0.939",
        "Quotient": "1.292",
        "OrderNo": "2",
        "IsQualified": null,
        "LeadBy": "0",
        "Deficit": "0",
        "Performance": "W,W,L,L,W",
        "Status": "SAME",
        "MATCH_ID": "894",
        "PrevPosition": "2"
    },
    {
        "StandingFlag": "NET",
        "Category": null,
        "CompetitionID": "107",
        "TeamID": "77",
        "TeamCode": "LSG",
        "TeamName": "Lucknow Super Giants",
        "TeamLogo": "https://scores.iplt20.com/ipl/teamlogos/LSG.png",
        "Matches": "8",
        "Wins": "5",
        "Loss": "3",
        "Tied": "0",
        "NoResult": "0",
        "Points": "10",
        "Draw": "0",
        "ForTeams": "1436/156.0",
        "AgainstTeam": "1334/159.3",
        "NetRunRate": "0.841",
        "Quotient": "1.116",
        "OrderNo": "3",
        "IsQualified": null,
        "LeadBy": "0",
        "Deficit": "0",
        "Performance": "W,L,W,L,W",
        "Status": "SAME",
        "MATCH_ID": "894",
        "PrevPosition": "3"
    },
    {
        "StandingFlag": "NET",
        "Category": null,
        "CompetitionID": "107",
        "TeamID": "13",
        "TeamCode": "CSK",
        "TeamName": "Chennai Super Kings",
        "TeamLogo": "https://scores.iplt20.com/ipl/teamlogos/CSK.png",
        "Matches": "8",
        "Wins": "5",
        "Loss": "3",
        "Tied": "0",
        "NoResult": "0",
        "Points": "10",
        "Draw": "0",
        "ForTeams": "1495/156.5",
        "AgainstTeam": "1459/159.2",
        "NetRunRate": "0.376",
        "Quotient": "1.366",
        "OrderNo": "4",
        "IsQualified": null,
        "LeadBy": "0",
        "Deficit": "0",
        "Performance": "L,W,W,W,L",
        "Status": "SAME",
        "MATCH_ID": "894",
        "PrevPosition": "4"
    },
    {
        "StandingFlag": "NET",
        "Category": null,
        "CompetitionID": "107",
        "TeamID": "19",
        "TeamCode": "RCB",
        "TeamName": "Royal Challengers Bangalore",
        "TeamLogo": "https://scores.iplt20.com/ipl/teamlogos/RCB.png",
        "Matches": "8",
        "Wins": "4",
        "Loss": "4",
        "Tied": "0",
        "NoResult": "0",
        "Points": "8",
        "Draw": "0",
        "ForTeams": "1441/156.2",
        "AgainstTeam": "1497/160.0",
        "NetRunRate": "-0.139",
        "Quotient": "1.159",
        "OrderNo": "5",
        "IsQualified": null,
        "LeadBy": "0",
        "Deficit": "0",
        "Performance": "W,L,W,W,L",
        "Status": "SAME",
        "MATCH_ID": "894",
        "PrevPosition": "5"
    },
    {
        "StandingFlag": "NET",
        "Category": null,
        "CompetitionID": "107",
        "TeamID": "15",
        "TeamCode": "PBKS",
        "TeamName": "Punjab Kings",
        "TeamLogo": "https://scores.iplt20.com/ipl/teamlogos/PBKS.png",
        "Matches": "8",
        "Wins": "4",
        "Loss": "4",
        "Tied": "0",
        "NoResult": "0",
        "Points": "8",
        "Draw": "0",
        "ForTeams": "1372/155.3",
        "AgainstTeam": "1428/153.0",
        "NetRunRate": "-0.510",
        "Quotient": "0.666",
        "OrderNo": "6",
        "IsQualified": null,
        "LeadBy": "0",
        "Deficit": "0",
        "Performance": "L,W,L,W,L",
        "Status": "SAME",
        "MATCH_ID": "894",
        "PrevPosition": "6"
    },
    {
        "StandingFlag": "NET",
        "Category": null,
        "CompetitionID": "107",
        "TeamID": "16",
        "TeamCode": "KKR",
        "TeamName": "Kolkata Knight Riders",
        "TeamLogo": "https://scores.iplt20.com/ipl/teamlogos/KKR.png",
        "Matches": "9",
        "Wins": "3",
        "Loss": "6",
        "Tied": "0",
        "NoResult": "0",
        "Points": "6",
        "Draw": "0",
        "ForTeams": "1639/176.0",
        "AgainstTeam": "1616/170.5",
        "NetRunRate": "-0.147",
        "Quotient": "0.776",
        "OrderNo": "7",
        "IsQualified": null,
        "LeadBy": "0",
        "Deficit": "0",
        "Performance": "L,L,L,W,L",
        "Status": "SAME",
        "MATCH_ID": "894",
        "PrevPosition": "7"
    },
    {
        "StandingFlag": "NET",
        "Category": null,
        "CompetitionID": "107",
        "TeamID": "20",
        "TeamCode": "SRH",
        "TeamName": "Sunrisers Hyderabad",
        "TeamLogo": "https://scores.iplt20.com/ipl/teamlogos/SRH.png",
        "Matches": "8",
        "Wins": "3",
        "Loss": "5",
        "Tied": "0",
        "NoResult": "0",
        "Points": "6",
        "Draw": "0",
        "ForTeams": "1271/157.1",
        "AgainstTeam": "1340/154.4",
        "NetRunRate": "-0.577",
        "Quotient": "0.911",
        "OrderNo": "8",
        "IsQualified": null,
        "LeadBy": "0",
        "Deficit": "0",
        "Performance": "W,L,L,L,W",
        "Status": "UP",
        "MATCH_ID": "894",
        "PrevPosition": "9"
    },
    {
        "StandingFlag": "NET",
        "Category": null,
        "CompetitionID": "107",
        "TeamID": "17",
        "TeamCode": "MI",
        "TeamName": "Mumbai Indians",
        "TeamLogo": "https://scores.iplt20.com/ipl/teamlogos/MI.png",
        "Matches": "7",
        "Wins": "3",
        "Loss": "4",
        "Tied": "0",
        "NoResult": "0",
        "Points": "6",
        "Draw": "0",
        "ForTeams": "1232/137.4",
        "AgainstTeam": "1287/134.3",
        "NetRunRate": "-0.620",
        "Quotient": "0.979",
        "OrderNo": "9",
        "IsQualified": null,
        "LeadBy": "0",
        "Deficit": "0",
        "Performance": "W,W,W,L,L",
        "Status": "DOWN",
        "MATCH_ID": "894",
        "PrevPosition": "8"
    },
    {
        "StandingFlag": "NET",
        "Category": null,
        "CompetitionID": "107",
        "TeamID": "14",
        "TeamCode": "DC",
        "TeamName": "Delhi Capitals",
        "TeamLogo": "https://scores.iplt20.com/ipl/teamlogos/DC.png",
        "Matches": "8",
        "Wins": "2",
        "Loss": "6",
        "Tied": "0",
        "NoResult": "0",
        "Points": "4",
        "Draw": "0",
        "ForTeams": "1230/159.2",
        "AgainstTeam": "1363/158.1",
        "NetRunRate": "-0.898",
        "Quotient": "0.628",
        "OrderNo": "10",
        "IsQualified": null,
        "LeadBy": "0",
        "Deficit": "0",
        "Performance": "L,L,W,W,L",
        "Status": "SAME",
        "MATCH_ID": "894",
        "PrevPosition": "10"
    }
]

// # react redux intergartion --

// # context -- 

// # props driiling  
// # use state use reducer



// step 1 install redux react-redux 

// step2 .you have to configure redux 
//         1. create store 
//         2. cretae reducer 
//         3. create root reducer
//         4. on click of any acytion dispath it to reducer 

// action -----any task 

// dispatch ----through dispatch we'll send action/ data to reducer

// reducer ----is a function that will update the state / store return new state always

// store ---central collection of data

// redux ----third party library to manage state in react application